from .usuarioView import UsuarioListCreateView, UsuarioRetrieveUpdateDeleteView
from .medicoView import MedicoListCreateView, MedicoRetrieveUpdateView
from .pacienteView import createpaciente, detailpaciente
from .UserCreateView import usercreateview